apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "ethereum.fullname" . }}-artifacts-pvc
  labels:
    app: {{ template "ethereum.name" . }}
    chart: {{ template "ethereum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: artifacts-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
