apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ethereum.fullname" . }}-geth-account
  labels:
    app: {{ template "ethereum.name" . }}
    chart: {{ template "ethereum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  accountSecret: {{ .Values.geth.account.secret | b64enc | quote }}
  gethtx1NodeKey: {{ .Values.geth.account.gethtx1.nodeKey | b64enc | quote }}
  gethtx2NodeKey: {{ .Values.geth.account.gethtx2.nodeKey | b64enc | quote }}
  gethtx3NodeKey: {{ .Values.geth.account.gethtx3.nodeKey | b64enc | quote }}
  gethtx4NodeKey: {{ .Values.geth.account.gethtx4.nodeKey | b64enc | quote }}
  gethblockscouttxNodeKey: {{ .Values.geth.account.gethblockscouttx.nodeKey | b64enc | quote }}
  {{ if eq (.Values.geth.validators | toString) "og" }}
  gethminer1PrivateKey: {{ .Values.geth.account.gethminer1.privateKey | b64enc | quote }}
  gethminer2PrivateKey: {{ .Values.geth.account.gethminer2.privateKey | b64enc | quote }}
  gethminer3PrivateKey: {{ .Values.geth.account.gethminer3.privateKey | b64enc | quote }}
  gethminer4PrivateKey: {{ .Values.geth.account.gethminer4.privateKey | b64enc | quote }}
  {{ end }}
  mnemonic: {{ .Values.mnemonic | b64enc }}
