steps:
  
- name: gcr.io/kaniko-project/executor:latest
  args: [
    "--dockerfile=dockerfiles/monorepo/Dockerfile.celotool",
    "--cache=true",
    "--destination=gcr.io/$PROJECT_ID/celo-monorepo:celotool-$COMMIT_SHA"
  ]

- name: gcr.io/kaniko-project/executor:latest
  args: [
    "--dockerfile=dockerfiles/monorepo/Dockerfile.transaction-metrics-exporter",
    "--cache=true",
    "--destination=gcr.io/$PROJECT_ID/celo-monorepo:transaction-metrics-exporter-$COMMIT_SHA"
  ]

timeout: 3000s
