apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.environment }}-load-test-secrets
  labels:
    app: load-test
    chart: load-test
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: load-test
type: Opaque
data:
  mnemonic: {{ .Values.mnemonic | b64enc }}
