apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-blockscout
  labels:
    app: blockscout
    chart: blockscout
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.blockscout.db.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.blockscout.db.password | b64enc | quote }}
