apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: blockscout
    chart: blockscout
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: blockscout-web
spec:
  selector:
    app: blockscout
    release: {{ .Release.Name }}
    component: blockscout-web
  clusterIP: None
  ports:
  - name: http
    port: 4000
